name: Autograding

on:
  push:
    branches:
      - main

jobs:
  testCircle:
    name: Test Circle Class
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
  
      - name: Build with Gradle
        run: ./gradlew build -x test
  
      - name: Run Circle tests
        run: ./gradlew test --tests "com.example.CircleTest"

  testSquare:
    name: Test Square Class
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
  
      - name: Build with Gradle
        run: ./gradlew build -x test
  
      - name: Run Square tests
        run: ./gradlew test --tests "com.example.SquareTest"

  testTriangle:
    name: Test Triangle Class
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
  
      - name: Build with Gradle
        run: ./gradlew build -x test
  
      - name: Run Triangle tests
        run: ./gradlew test --tests "com.example.TriangleTest"

  testStudent:
    name: Test Student Class
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
  
      - name: Build with Gradle
        run: ./gradlew build -x test
  
      - name: Run Student tests
        run: ./gradlew test --tests "com.example.StudentTest"

  testCourse:
    name: Test Course Class
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
  
      - name: Build with Gradle
        run: ./gradlew build -x test
  
      - name: Run Course tests
        run: ./gradlew test --tests "com.example.CourseTest"